%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(cuter_proto_erlang_term).
-define(cuter_proto_erlang_term, true).

-define(cuter_proto_erlang_term_gpb_version, "3.26.4").

-ifndef('ERLANGTERM.MAPENTRY_PB_H').
-define('ERLANGTERM.MAPENTRY_PB_H', true).
-record('ErlangTerm.MapEntry',
        {key,                           % = 1, {msg,'ErlangTerm'} (optional)
         value                          % = 2, {msg,'ErlangTerm'} (optional)
        }).
-endif.

-ifndef('ERLANGTERM.FUNENTRY_PB_H').
-define('ERLANGTERM.FUNENTRY_PB_H', true).
-record('ErlangTerm.FunEntry',
        {arguments = [],                % = 1, [{msg,'ErlangTerm'}]
         value                          % = 2, {msg,'ErlangTerm'} (optional)
        }).
-endif.

-ifndef('ERLANGTERM_PB_H').
-define('ERLANGTERM_PB_H', true).
-record('ErlangTerm',
        {type,                          % = 1, {enum,'ErlangTerm.Type'} (optional)
         value,                         % = 2, string (optional)
         subterms = [],                 % = 3, [{msg,'ErlangTerm'}]
         shared = [],                   % = 4, [{map,string,{msg,'ErlangTerm'}}]
         improper_list_nil,             % = 5, {msg,'ErlangTerm'} (optional)
         atom_chars = [],               % = 6, [int32]
         bits = [],                     % = 7, [bool]
         map_entries = [],              % = 8, [{msg,'ErlangTerm.MapEntry'}]
         points = [],                   % = 9, [{msg,'ErlangTerm.FunEntry'}]
         otherwise,                     % = 10, {msg,'ErlangTerm'} (optional)
         arity                          % = 11, int32 (optional)
        }).
-endif.

-endif.
