# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cuter_proto_solver_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cuter_proto_erlang_term_pb2 as cuter__proto__erlang__term__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cuter_proto_solver_response.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n!cuter_proto_solver_response.proto\x1a\x1d\x63uter_proto_erlang_term.proto\"\xea\x02\n\x0eSolverResponse\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.SolverResponse.Type\x12(\n\x06status\x18\x02 \x01(\x0e\x32\x16.SolverResponse.StatusH\x00\x12&\n\x05model\x18\x03 \x01(\x0b\x32\x15.SolverResponse.ModelH\x00\x1a\x42\n\nModelEntry\x12\x18\n\x03var\x18\x01 \x01(\x0b\x32\x0b.ErlangTerm\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.ErlangTerm\x1a\x34\n\x05Model\x12+\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.SolverResponse.ModelEntry\"(\n\x04Type\x12\x10\n\x0cMODEL_STATUS\x10\x00\x12\x0e\n\nMODEL_DATA\x10\x01\"6\n\x06Status\x12\x07\n\x03SAT\x10\x00\x12\t\n\x05UNSAT\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x12\x0b\n\x07TIMEOUT\x10\x03\x42\x06\n\x04\x64\x61tab\x06proto3')
  ,
  dependencies=[cuter__proto__erlang__term__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SOLVERRESPONSE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='SolverResponse.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODEL_STATUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODEL_DATA', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=327,
  serialized_end=367,
)
_sym_db.RegisterEnumDescriptor(_SOLVERRESPONSE_TYPE)

_SOLVERRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='SolverResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SAT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSAT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=369,
  serialized_end=423,
)
_sym_db.RegisterEnumDescriptor(_SOLVERRESPONSE_STATUS)


_SOLVERRESPONSE_MODELENTRY = _descriptor.Descriptor(
  name='ModelEntry',
  full_name='SolverResponse.ModelEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='var', full_name='SolverResponse.ModelEntry.var', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='SolverResponse.ModelEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=271,
)

_SOLVERRESPONSE_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='SolverResponse.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='SolverResponse.Model.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=325,
)

_SOLVERRESPONSE = _descriptor.Descriptor(
  name='SolverResponse',
  full_name='SolverResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SolverResponse.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='SolverResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='SolverResponse.model', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SOLVERRESPONSE_MODELENTRY, _SOLVERRESPONSE_MODEL, ],
  enum_types=[
    _SOLVERRESPONSE_TYPE,
    _SOLVERRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='SolverResponse.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=69,
  serialized_end=431,
)

_SOLVERRESPONSE_MODELENTRY.fields_by_name['var'].message_type = cuter__proto__erlang__term__pb2._ERLANGTERM
_SOLVERRESPONSE_MODELENTRY.fields_by_name['value'].message_type = cuter__proto__erlang__term__pb2._ERLANGTERM
_SOLVERRESPONSE_MODELENTRY.containing_type = _SOLVERRESPONSE
_SOLVERRESPONSE_MODEL.fields_by_name['entries'].message_type = _SOLVERRESPONSE_MODELENTRY
_SOLVERRESPONSE_MODEL.containing_type = _SOLVERRESPONSE
_SOLVERRESPONSE.fields_by_name['type'].enum_type = _SOLVERRESPONSE_TYPE
_SOLVERRESPONSE.fields_by_name['status'].enum_type = _SOLVERRESPONSE_STATUS
_SOLVERRESPONSE.fields_by_name['model'].message_type = _SOLVERRESPONSE_MODEL
_SOLVERRESPONSE_TYPE.containing_type = _SOLVERRESPONSE
_SOLVERRESPONSE_STATUS.containing_type = _SOLVERRESPONSE
_SOLVERRESPONSE.oneofs_by_name['data'].fields.append(
  _SOLVERRESPONSE.fields_by_name['status'])
_SOLVERRESPONSE.fields_by_name['status'].containing_oneof = _SOLVERRESPONSE.oneofs_by_name['data']
_SOLVERRESPONSE.oneofs_by_name['data'].fields.append(
  _SOLVERRESPONSE.fields_by_name['model'])
_SOLVERRESPONSE.fields_by_name['model'].containing_oneof = _SOLVERRESPONSE.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['SolverResponse'] = _SOLVERRESPONSE

SolverResponse = _reflection.GeneratedProtocolMessageType('SolverResponse', (_message.Message,), dict(

  ModelEntry = _reflection.GeneratedProtocolMessageType('ModelEntry', (_message.Message,), dict(
    DESCRIPTOR = _SOLVERRESPONSE_MODELENTRY,
    __module__ = 'cuter_proto_solver_response_pb2'
    # @@protoc_insertion_point(class_scope:SolverResponse.ModelEntry)
    ))
  ,

  Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
    DESCRIPTOR = _SOLVERRESPONSE_MODEL,
    __module__ = 'cuter_proto_solver_response_pb2'
    # @@protoc_insertion_point(class_scope:SolverResponse.Model)
    ))
  ,
  DESCRIPTOR = _SOLVERRESPONSE,
  __module__ = 'cuter_proto_solver_response_pb2'
  # @@protoc_insertion_point(class_scope:SolverResponse)
  ))
_sym_db.RegisterMessage(SolverResponse)
_sym_db.RegisterMessage(SolverResponse.ModelEntry)
_sym_db.RegisterMessage(SolverResponse.Model)


# @@protoc_insertion_point(module_scope)
