# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cuter_proto_solver_command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cuter_proto_erlang_term_pb2 as cuter__proto__erlang__term__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cuter_proto_solver_command.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n cuter_proto_solver_command.proto\x1a\x1d\x63uter_proto_erlang_term.proto\"\x92\x02\n\rSolverCommand\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.SolverCommand.Type\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x15\n\rto_constraint\x18\x03 \x01(\x03\x12\x1c\n\x07symbvar\x18\x04 \x01(\x0b\x32\x0b.ErlangTerm\x12\"\n\rsymbvar_value\x18\x05 \x01(\x0b\x32\x0b.ErlangTerm\"s\n\x04Type\x12\x13\n\x0fLOAD_TRACE_FILE\x10\x00\x12\t\n\x05SOLVE\x10\x01\x12\r\n\tGET_MODEL\x10\x02\x12\x0e\n\nADD_AXIOMS\x10\x03\x12\x10\n\x0c\x46IX_VARIABLE\x10\x04\x12\x10\n\x0cRESET_SOLVER\x10\x05\x12\x08\n\x04STOP\x10\x06\x62\x06proto3')
  ,
  dependencies=[cuter__proto__erlang__term__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SOLVERCOMMAND_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='SolverCommand.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOAD_TRACE_FILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOLVE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_MODEL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_AXIOMS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIX_VARIABLE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET_SOLVER', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=227,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_SOLVERCOMMAND_TYPE)


_SOLVERCOMMAND = _descriptor.Descriptor(
  name='SolverCommand',
  full_name='SolverCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SolverCommand.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='SolverCommand.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_constraint', full_name='SolverCommand.to_constraint', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbvar', full_name='SolverCommand.symbvar', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbvar_value', full_name='SolverCommand.symbvar_value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SOLVERCOMMAND_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=342,
)

_SOLVERCOMMAND.fields_by_name['type'].enum_type = _SOLVERCOMMAND_TYPE
_SOLVERCOMMAND.fields_by_name['symbvar'].message_type = cuter__proto__erlang__term__pb2._ERLANGTERM
_SOLVERCOMMAND.fields_by_name['symbvar_value'].message_type = cuter__proto__erlang__term__pb2._ERLANGTERM
_SOLVERCOMMAND_TYPE.containing_type = _SOLVERCOMMAND
DESCRIPTOR.message_types_by_name['SolverCommand'] = _SOLVERCOMMAND

SolverCommand = _reflection.GeneratedProtocolMessageType('SolverCommand', (_message.Message,), dict(
  DESCRIPTOR = _SOLVERCOMMAND,
  __module__ = 'cuter_proto_solver_command_pb2'
  # @@protoc_insertion_point(class_scope:SolverCommand)
  ))
_sym_db.RegisterMessage(SolverCommand)


# @@protoc_insertion_point(module_scope)
